export const MASTER_SEAN_CHAN_SLUGS = [
  "iching-hexagram-1-qian",
  "iching-hexagram-2-kun",
  "iching-hexagram-3-zhun",
  "iching-hexagram-4-meng",
  "iching-hexagram-5-xu",
  "iching-hexagram-6-song",
  "iching-hexagram-7-shi",
  "iching-hexagram-8-bi",
  "iching-hexagram-9-xiao-xu",
  "iching-hexagram-10-lu",
  "iching-hexagram-11-tai",
  "iching-hexagram-12-pi",
  "iching-hexagram-13-tong-ren",
  "iching-hexagram-14-da-you",
  "iching-hexagram-15-qian-modesty",
  "iching-hexagram-16-yu",
  "iching-hexagram-17-sui",
  "iching-hexagram-18-gu",
  "iching-hexagram-19-lin",
  "iching-hexagram-20-guan",
  "iching-hexagram-21-shi-he",
  "iching-hexagram-22-bi-grace",
  "iching-hexagram-23-bo",
  "iching-hexagram-24-fu",
  "iching-hexagram-25-wu-wang",
  "iching-hexagram-26-da-xu",
  "iching-hexagram-27-yi",
  "iching-hexagram-28-da-guo",
  "iching-hexagram-29-kan",
  "iching-hexagram-30-li",
  "iching-hexagram-31-xian",
  "iching-hexagram-32-heng",
  "iching-hexagram-33-dun",
  "iching-hexagram-34-da-zhuang",
  "iching-hexagram-35-jin",
  "iching-hexagram-36-ming-yi",
  "iching-hexagram-37-jia-ren",
  "iching-hexagram-38-kui",
  "iching-hexagram-39-jian-obstruction",
  "iching-hexagram-40-jie",
  "iching-hexagram-41-sun",
  "iching-hexagram-42-yi-increase",
  "iching-hexagram-43-guai",
  "iching-hexagram-44-gou",
  "iching-hexagram-45-cui",
  "iching-hexagram-46-sheng",
  "iching-hexagram-47-kun-oppression",
  "iching-hexagram-48-jing",
  "iching-hexagram-49-ge",
  "iching-hexagram-50-ding",
  "iching-hexagram-51-zhen",
  "iching-hexagram-52-gen",
  "iching-hexagram-53-jian-development",
  "iching-hexagram-54-gui-mei",
  "iching-hexagram-55-feng",
  "iching-hexagram-56-lu-traveler",
  "iching-hexagram-57-xun",
  "iching-hexagram-58-dui",
  "iching-hexagram-59-huan",
  "iching-hexagram-60-jie-limitation",
  "iching-hexagram-61-zhong-fu",
  "iching-hexagram-62-xiao-guo",
  "iching-hexagram-63-ji-ji",
  "iching-hexagram-64-wei-ji",
] as const;

const ICHING_OMENS = [
  "Khốn Long Đắc Thủy, Thời Vận Đã Đến",
  "Ngạ Hổ Đắc Thực, Thỏa Lòng Mãn Ý",
  "Loạn Ti Vô Đầu, Lòng Dạ Rối Bời",
  "Tiểu Quỷ Thâu Tiền, Thời Vận Không Hay",
  "Minh Châu Xuất Thổ, Vận Tốt Đã Đến",
  "Nhị Nhân Tranh Lộ, Việc Làm Không Thuận",
  "Mã Đáo Thành Công, Mọi Sự Tốt Đẹp",
  "Thuận Phong Hành Thuyền, Việc Gì Cũng Lợi",
  "Mật Vân Bất Vũ, Tạm Thời Phải Nhẫn",
  "Phượng Minh Kỳ Sơn, Quốc Gia Cát Tường",
  "Hỷ Báo Tam Nguyên, Đại Cát Đại Lợi",
  "Hổ Lạc Hãm Khanh, Cát Ít Hung Nhiều",
  "Tiên Nhân Chỉ Lộ, Đi Đâu Cũng Lợi",
  "Nhuyễn Mộc Nô Tước, Làm Việc Chắc Chắn",
  "Nhị Nhân Phân Kim, Vạn Sự Hanh Thông",
  "Thanh Long Đắc Vị, Gặp Hung Hóa Cát",
  "Bộ Bộ Đăng Cao, Lên Cao Từng Bước",
  "Thôi Ma Phần Đạo, Làm Không Đúng Cách",
  "Phát Chánh Thi Nhân, Thời Vận Hanh Thông",
  "Hạn Bồng Phùng Hà, Quý Nhân Phù Trợ",
  "Cô Nhân Ngộ Thực, Gặp May Mắn",
  "Hỷ Khí Doanh Môn, Vạn Sự Như Ý",
  "Ưng Thước Đồng Lâm, Việc Không Thành",
  "Phu Thê Phản Mục, Tráo Trở Lật Lọng",
  "Điểu Bị Lao Lung, Tù Túng Buồn Lo",
  "Trận Thế Đắc Khai, Không Còn Trở Ngại",
  "Vị Thủy Phỏng Hiền, Bĩ Cực Thái Lai",
  "Dạ Mộng Kim Ngân, Không Vẫn Hoàn Không",
  "Thủy Để Lao Nguyệt, Uổng Công Phí Sức",
  "Thiên Quan Tứ Phước, Phát Phúc Sinh Tài",
  "Manh Nha Xuất Thổ, Thời Vận Đã Đến",
  "Ngư Lai Tràng Võng, Vạn Sự Như Ý",
  "Nùng Vân Tế Nhật, Mưu Sự Bất Thành",
  "Công Sư Đắc Mộc, Vận Khí Sắp Lên",
  "Sừ Địa Đắc Kim, Vận Đỏ Sắp Đến",
  "Quá Giang Chiết Kiều, Vô Cùng Khó Khăn",
  "Cảnh Lý Quan Hoa, Theo Đuổi Ảo Ảnh",
  "Phản Mại Trư Dương, Long Đong Lận Đận",
  "Vũ Tuyết Tải Đồ, Mưu Sự Không Đúng",
  "Ngũ Quan Thoát Nạn, May Mắn Thoát Nạn",
  "Thôi Xa Phí Lực, Uổng Phí Công Sức",
  "Khô Mộc Khai Hoa, Bĩ Cực Vinh Lai",
  "Du Phong Thoát Võng, Gặp Hung Hóa Cát",
  "Tha Hương Ngộ Hữu, Thời Vận Đã Đến",
  "Ngư Lý Hóa Long, Rồng Bay Lên Trời",
  "Chỉ Nhật Cao Thăng, Phát Tài Phát Lộc",
  "Thoát Lãng Trừu Đê, Tình Trạng Bất Ổn",
  "Khô Tỉnh Sanh Tuyền, Vận Tốt Đã Đến",
  "Hạn Miêu Đắc Vũ, Vận Tốt Đã Đến",
  "Ngư Ông Đắc Lợi, Nhất Cử Lưỡng Tiện",
  "Kim Chung Dạ Tràng, Mọi Sự Thành Công",
  "Nhân Đoản Táo Cao, Mọi Việc Bất Thuận",
  "Tuấn Mã Xuất Lung, Trứng Để Đầu Đẳng",
  "Duyên Mộc Cầu Ngư, Mưu Sự Bất Thành",
  "Cổ Kính Trùng Minh, Vận Tốt Trở Lại",
  "Túc Điểu Phần Sào, Việc Làm Không Thành",
  "Châu Đắc Thuận Phong, Khốn Cực Sinh Phúc",
  "Chẩn Thủy Hòa Nê, Vô Cùng Thuận Tiện",
  "Cách Hà Vọng Kim, Uổng Công Phí Sức",
  "Trảm Tướng Phong Thần, Không Phải Kiêng Kị",
  "Hành Tẩu Bạc Băng, Vô Cùng Tốt Lành",
  "Cấp Quá Độc Kiều, Tiến Lợi Lui Hại",
  "Kim Bảng Đề Danh, Cát Khánh Như Ý",
  "Thái Tuế Nguyệt Kiến, Tiểu Nhân Ám Hại",
] as const;

const VIETNAMESE_KEYWORDS = [
  "sáng tạo, chủ động, quyền uy, lãnh đạo, khởi đầu, mạnh mẽ, bền bỉ, thời vận",
  "tiếp nhận, nhu thuận, nuôi dưỡng, kiên nhẫn, hậu thuẫn, ổn định, bao dung, thuận thời",
  "khởi đầu khó, rối ren, khai mở, kiên trì, thử thách, non yếu, dựng nền, tháo gỡ",
  "mông muội, học hỏi, non dại, thiếu sáng suốt, cẩn trọng, giáo hóa, tránh lừa dối, sửa sai",
  "chờ thời, nhẫn nại, dưỡng sức, chuẩn bị, giữ trung đạo, tin tưởng, đúng lúc, bền chí",
  "tranh chấp, kiện tụng, bất hòa, phòng thủ, nhượng bộ, xem lại động cơ, tránh đối đầu, giữ chính",
  "kỷ luật, chiến lược, tổ chức, lãnh đạo, huy động lực lượng, trách nhiệm, chính danh, thành công",
  "liên kết, hợp tác, đoàn kết, chọn phe, tín nhiệm, tương trợ, cộng đồng, đồng lòng",
  "tích lũy nhỏ, kiềm chế, chuẩn bị, nuôi dưỡng, trở ngại nhẹ, mềm mỏng, chờ mưa, bền bỉ",
  "lễ nghi, thận trọng, cư xử đúng, tự biết mình, bước trên hiểm, trách nhiệm, nhạy cảm, giữ lễ",
  "hanh thông, hòa hợp, cân bằng, thịnh vượng, mở rộng, thuận lợi, giao thái, an ổn",
  "bế tắc, đình trệ, xa cách, bất tín, thu mình, thời xấu, giữ đạo, chờ chuyển",
  "đồng hành, cộng tác, minh bạch, lý tưởng chung, kết nối, tôn trọng, mở lòng, cùng chí hướng",
  "đại hữu, sung túc, thành tựu, biết ơn, chia sẻ, của cải, uy tín, quản trị nguồn lực",
  "khiêm nhường, giản dị, tự trọng, điều độ, chân thành, giảm cái tôi, đáng tin, cân bằng",
  "hứng khởi, cổ vũ, tự tin, lan tỏa, chuẩn bị, hưởng ứng, khởi động, cảm hứng",
  "thuận theo, thích nghi, tín nhiệm, phục vụ, dẫn dắt mềm, nhận chỉ dẫn, trung thành, hợp tác",
  "sửa sai, chữa lành, thanh lọc, xử lý quá khứ, trách nhiệm, cải tổ, khôi phục, dọn mục nát",
  "tiến gần, nâng đỡ, cơ hội, ảnh hưởng tăng, ấm áp, khai mở, chỉ dẫn, thời vận lên",
  "quan sát, chiêm nghiệm, nhìn xa, tĩnh lặng, hiểu biết, soi xét, phản tư, định hướng",
  "quyết đoán, xử lý vướng mắc, công lý, kỷ luật, cắt bỏ, thi hành, bền nhiệm vụ, rõ ràng",
  "vẻ đẹp, trang nhã, hình thức, duyên dáng, biểu đạt, soi nội tâm, hấp dẫn, tránh phù phiếm",
  "tan rã, bóc tách, buông bỏ, suy sụp, kết thúc, loại cũ, nhẫn nhịn, bảo toàn",
  "quay về, khởi chu kỳ mới, phục hồi, đúng thời, tái sinh, cải thiện dần, trở lại đạo, hy vọng",
  "vô tư, nguyên bản, bất ngờ, thành thật, đơn giản, mở lòng, tự nhiên, tránh toan tính",
  "đại súc, tích đức, tự chủ, tập trung, nội lực, rèn tính, tiềm năng, kiềm chế",
  "nuôi dưỡng, lời nói, sức khỏe, quân bình, tự chăm sóc, chăm người, tinh thần, khẩu nghiệp",
  "quá tải, áp lực, gánh nặng, điểm gãy, quyết định lớn, chịu đựng, ưu tư, cân bằng lại",
  "hiểm nguy, vực sâu, sợ hãi, can đảm, lặp thử thách, giữ lòng tin, linh hoạt, thận trọng",
  "sáng tỏ, bám víu đúng, đam mê, khai sáng, văn minh, tái sinh, đạo đức, soi đường",
  "cảm ứng, thu hút, tình cảm, giao cảm, kích hoạt, chân thành, kết nối, duyên tình",
  "bền vững, kiên định, lâu dài, trưởng thành, cam kết, ổn định, nhịp đều, bền chí",
  "rút lui, tránh hiểm, buông bỏ, đánh giá lại, nghỉ ngơi, giữ sức, lui đúng lúc, bảo toàn",
  "đại tráng, sức mạnh, uy quyền, tự tin, lãnh đạo, chính trực, tiết chế lực, khí thế",
  "tiến lên, công nhận, sáng rõ, thành tựu, tăng tốc, được nâng đỡ, phát triển, mở vận",
  "ẩn sáng, giữ thấp, tự bảo vệ, khó khăn, nhẫn nhịn, nhìn vào trong, kín đáo, qua đêm tối",
  "gia đình, huyết thống, cộng đồng, vai trò, nề nếp, thân tình, tổ tiên, quan hệ gần",
  "đối lập, khác biệt, hiểu lầm, lệch pha, giữ cá tính, tìm điểm chung, bất hòa, khoảng cách",
  "trở ngại, đình trệ, thất vọng, khó tiến, tìm trợ lực, đổi hướng, kiên nhẫn, vượt khó",
  "giải thoát, tháo gỡ, nhẹ nhõm, cách tiếp cận mới, hết tắc, tha thứ, phấn chấn, mở nút",
  "giảm bớt, tiết chế, hy sinh, giản lược, bớt tham, tháo bỏ, tiết kiệm, lấy ít làm đủ",
  "gia tăng, phúc lợi, mở rộng, sinh sôi, chia sẻ, thuận lợi, khích lệ, đất lành",
  "quyết liệt, dứt khoát, chính trực, tự xét, phá vỡ, công bố, tập trung, không thỏa hiệp",
  "gặp gỡ, cám dỗ, hấp lực, cảnh giác, nửa đường gặp, liên kết mạnh, dục tính, kiểm soát",
  "tụ hội, quy tụ, hợp lực, cộng hưởng, nghi lễ, lãnh đạo nhóm, gom nguồn lực, sức mạnh tập thể",
  "thăng tiến, tiến từng bước, tự tin, nhận thử thách, được công nhận, leo lên, bền bỉ, phát triển",
  "khốn cùng, kiệt sức, hạn chế, cô lập, thiếu nguồn lực, chịu phạt, nội lực, giữ lời",
  "giếng nước, nguồn sống, trí tuệ, chân lý, trực giác, quay về nguồn, đào sâu, nuôi cộng đồng",
  "cải cách, lột xác, thay đổi lớn, bỏ cũ, cách mạng, chuyển hóa, bước nhảy, tái lập",
  "đỉnh, luyện hóa, tinh luyện, làm chủ, đổi mới tinh thần, chứa đựng, hiến dâng, trí tuệ",
  "chấn động, khủng hoảng, thức tỉnh, biến động, sợ mà tỉnh, quyền năng, bất ngờ, đổi nhịp",
  "tĩnh lặng, thiền định, dừng lại, tự chấp nhận, bình thản, tách rời, nghỉ ngơi, an nhiên",
  "tiệm tiến, chậm mà chắc, thích nghi, tuần tự, truyền thống, bền bỉ, trưởng thành, tiến xa",
  "quy muội, thế yếu, thỏa hiệp, cám dỗ, lệ thuộc, tự trọng thấp, quan hệ lệch, thận trọng",
  "phong thịnh, sung mãn, hào phóng, thu hoạch, chín muồi, giàu bên trong, đỉnh cao, dư dật",
  "lữ hành, xa lạ, di chuyển, phiêu lưu, độc hành, thích nghi, hành hương, mở tầm nhìn",
  "thẩm thấu, mềm mà sâu, gió, niềm tin, ôn hòa, ảnh hưởng tinh tế, hiểu biết, bất bạo động",
  "vui vẻ, giao tiếp, hồ hởi, thiện chí, thuyết phục mềm, biểu đạt, tương tác, hưởng lạc đúng",
  "tan rã tiêu cực, giải tỏa, hòa hợp, lưu thông, hồi sinh, phá ảo tưởng, nhẹ lòng, phân tán",
  "tiết chế, giới hạn, kỷ luật, nghi thức, kiên nhẫn, tích năng lượng, trưởng thành, tự trọng",
  "trung phu, chân thành, trực giác, sáng trong, trí tim, xuyên ảo ảnh, niềm tin, ý thức",
  "tiểu quá, chi tiết, khiêm nhỏ, thận trọng, chậm lại, việc thường, tinh tế, không vượt mức",
  "đã xong, thành tựu, hoàn tất, đỉnh cao, cẩn trọng, duy trì, thắng lợi, việc trọn",
  "chưa xong, bất định, do dự, chưa ổn, cẩn thận, giữ niềm tin, chuẩn bị, chờ hoàn tất",
] as const;

const ENGLISH_KEYWORDS = [
  "active yang principle, strength, tenacity, dynamism, inspiration, heaven, masculinity, authority, father",
  "yielding yin principle, devoted, patient, supportive, obedient, responsive, intuitive, earthy, mother",
  "growing pains, doubts and fears, awkwardness, becoming stronger, vulnerability, inexperience",
  "impulsiveness, immaturity, bluffing, ignorance, learning, impatience, reckless behavior",
  "perseverance, take care of essentials, restraint, leave well enough alone, moderation, right timing",
  "will-to-power, hostility, jealousy, stubbornness, aggression, fear, competitiveness, controversy",
  "exert authority, define, take the bull by the horns, create a strategy, mobilize forces",
  "union, cooperation, solidarity, membership, teamwork, participation, making a choice",
  "self-restraint, self-sufficiency, careful preparations, resourcefulness, minor impediments, adaptability",
  "conduct, self-awareness, proceed with caution and sensitivity, correct behavior, act responsibly",
  "harmony, balance, perfection, equipoise, sense of well-being, favorable conditions, expansion",
  "alienation, stalemate, stagnation, withholding, grinding to a halt, insensitivity, mistrust",
  "friendliness, mutual respect, shared goals, interdependence, agreement, strengthening bonds",
  "wealth, good fortune, success, express gratitude by supporting others, material possessions",
  "moderation, humility, keep it simple, lack of pretension, self-respect, sincerity, respectability",
  "self-expression, inspiring others, self-confidence, totality, success, sharing a positive response",
  "loyalty, adaptability, cooperation, trust, reliability, sensitivity to others, service, receiving guidance",
  "healing, correct past mistakes, make repairs, clean up corruption, restore balance, responsible action",
  "advancing, warm reception, prosperous conditions, increased influence, hopefulness, lightening up, arrival",
  "gaining overview, detached observation, increased understanding, solitude, integration through reflection",
  "take decisive action, restore order, force applied with sensitivity, justice, tenacious devotion to a task",
  "adornment, bring out beauty, elegance, outer as reflection of inner, vanity, charisma, self-expression",
  "impermanence, collapse, deterioration, separation, let go, surrender, eliminate the old, death",
  "return, start of a new cycle, right timing, regeneration, inevitability, steady improvements",
  "trusting nature, originality, spontaneity, open-heartedness, simplicity, the unexpected",
  "self-discipline, concentration, strengthen character from within, self-awareness, realizing potential",
  "nourishment, health, well-being, providing for others, creating balance, nurturing body, mind and spirit",
  "stress, overload, exhaustion, obsessiveness, gluttony, burdens, worries, breaking point",
  "danger, insecurity, overwhelm, unpredictability, hazardous conditions, dark emotions, facing fear, courage",
  "fire, illumination, inspiration, devotion, all-consuming passion, regeneration, spirituality, virtue, enlightenment",
  "courtship, mutual attraction, genuine affection, natural magnetism, stimulation, connecting",
  "constancy, continuity, endurance, perseverance, maturity, strengthening, stability, deep commitment",
  "timely departure, letting go, withdrawal, reevaluation, retirement, do not hesitate to walk away",
  "strength of character, authority, dignity, influence, self-confidence, leadership, peak condition, potency",
  "advancement, gaining recognition, appreciation, achievements, acceleration, steady gains, increased clarity",
  "maintain a low profile, look inward first, caution and moderation, difficulties, self-protection, subdue your brilliance",
  "heredity, blood bonds, kindred spirit, ancestry, home life, community, intimate relationships, human family",
  "opposite viewpoints, personal differences, communication gap, disharmony, misunderstandings, estrangement",
  "unexpected obstructions, frustration, difficulties, feelings of hopelessness, struggle, discouragement",
  "release, relief, fresh approach, liberation from obstruction, finding a solution, exhilaration",
  "decline, cutting back, frugality, contraction, letting go, less is more, resourcefulness, sacrifice",
  "sharing, reaping rewards, overflow, expansion, flowering, encouragement, fertile ground, abundance",
  "determination, no compromises, unwavering focus, inner resolve, integrity, test of character, self-examination",
  "seduction, temptation, magnetism, passionate encounter, meeting halfway, coupling, sexual union",
  "massing, converging, unifying, assembling, combining forces, sum is greater than the parts",
  "steady progress, gaining confidence, accepting challenges, promotion, receiving recognition",
  "restriction, exhaustion, depression, depleted resources, feeling cut off, punishment, confinement",
  "seeking truth, wisdom, insight, intuitive knowing, return to the source, getting to the bottom of things",
  "transformation, radical change, give up the old to make way for the new, quantum leap",
  "inner alchemy, mastery, spiritual renewal, consecrate, contain, rejuvenation, discerning wisdom",
  "shock, crisis, upheaval, awe inspiring, dramatic power shifts, unpredictability, shake-up wake-up",
  "meditation, self-renewal, composure, detachment, self-acceptance, equanimity, serenity",
  "gradual progress, continuity, slowly but surely, adaptability, time-honored approach",
  "compromising situation, subordination, succumbing to seduction, manipulation, low self-esteem",
  "plenty, profusion, generosity, fertility, ripeness, inner riches, reaping rewards, culmination, harvest",
  "traveling, adventure, movement, coping with unfamiliarity, pilgrimage, aloneness, broaden your horizons",
  "penetrating, soft approach, faith, moderation, subtle but deep influence, understanding, nonviolence",
  "happiness, delight, interaction, open communication, goodwill, friendly persuasion, self-expression",
  "diffuse negativity, restore harmony, circulate, revitalize, dissolve illusions, lighten up",
  "self-discipline, practice, self-respect, introspection, ritual, cultivate patience, build up energy, maturity",
  "wisdom of the heart, insight, clarity, purity, intuitive knowing, consciousness, penetrating illusion",
  "find extraordinary in the ordinary, keep it simple, use discretion, slow down, tend to details, pay attention",
  "final attainment, victory, crescendo, job well done, perfection, peak performance, prudence",
  "uncertainty, doubt and hesitation, loss of faith, unstable conditions, be extra cautious, discord",
] as const;

export const getIChingKeywords = (index: number) =>
  [
    `\u2714 ${ICHING_OMENS[index]}`,
    `\u2714 ${VIETNAMESE_KEYWORDS[index]}`,
    `\u2714 ${ENGLISH_KEYWORDS[index]}`,
  ].join("\n");
